
### Fonts Assets Build Process ###

# This process builds the required project fonts by embedding them into object
# files that are then linked and added to the project as an "assets_font"
# library, so the fonts are available in the final program binary.
# Additionally, a C/C++ header file is automatically generated to provide the
# different labels to access them.

###############################################################################

### Fonts Build ###

# Define and create fonts build directory
set(DIR_FONT_OBJECTS "${DIR_BUILD}/fonts")
file(MAKE_DIRECTORY "${DIR_FONT_OBJECTS}")

# Set fonts to build
file(GLOB FILES_FONT
    "${DIR_DEPS_FONTS}/nk57/*.otf"
)

# Build fonts
set(FONT_OBJECTS)
foreach(FONT_FILE IN LISTS FILES_FONT)
    get_filename_component(FONT_FILENAME "${FONT_FILE}" NAME_WE)
    get_filename_component(FONT_EXT "${FONT_FILE}" EXT)
    string(MAKE_C_IDENTIFIER "${FONT_FILENAME}${FONT_EXT}" FONT_NAME)

    message(STATUS "Adding font file: \"${FONT_NAME}\"")

    set(OBJ_FILE "${DIR_FONT_OBJECTS}/${FONT_NAME}.o")
    set(FONT_LOCAL "${DIR_FONT_OBJECTS}/${FONT_NAME}")

    add_custom_command(
        OUTPUT "${OBJ_FILE}"
        DEPENDS "${FONT_FILE}"
        WORKING_DIRECTORY "${DIR_FONT_OBJECTS}"

        COMMAND ${CMAKE_COMMAND}
                -E copy_if_different "${FONT_FILE}" "${FONT_LOCAL}"

        COMMAND ${CMAKE_LINKER}
                -r -b binary "${FONT_NAME}" -o "${OBJ_FILE}"

        COMMAND ${CMAKE_OBJCOPY}
                --strip-symbol=_binary_${FONT_NAME}_size "${OBJ_FILE}"

        COMMENT "Embedding font ${FONT_NAME}"
    )

    list(APPEND FONT_OBJECTS "${OBJ_FILE}")
endforeach()

# Set built fonts as library
add_library(assets_font STATIC ${FONT_OBJECTS})
set_target_properties(assets_font PROPERTIES LINKER_LANGUAGE C)

###############################################################################

### Generate C/C++ Header File ###

# Create assets directory if it doesn't exist
set(DIR_ASSETS_SRC ${DIR_SRC}/assets)
file(MAKE_DIRECTORY "${DIR_ASSETS_SRC}")

# Font header file path
set(FILE_FONT_HEADER "${DIR_ASSETS_SRC}/custom_fonts.h")

# Prepare font header content
set(FONT_HEADER_CONTENT
"
/*
 * NOTE: This File is automatically generated via CMake, changes will be
 * overwritten.
 */

/*****************************************************************************/

#pragma once

#include <cstddef>
#include <cstdint>
#include <cstring>

/*****************************************************************************/

/* Font Symbols */
")
foreach(FONT_FILE IN LISTS FILES_FONT)
    get_filename_component(FONT_FILENAME "${FONT_FILE}" NAME_WE)
    get_filename_component(FONT_EXT "${FONT_FILE}" EXT)
    string(MAKE_C_IDENTIFIER "${FONT_FILENAME}${FONT_EXT}" FONT_NAME)
    string(APPEND FONT_HEADER_CONTENT
"
// ${FONT_NAME}
extern \"C\"
{
    extern const unsigned char _binary_${FONT_NAME}_start[];
    extern const unsigned char _binary_${FONT_NAME}_end[];
}
inline const size_t _binary_${FONT_NAME}_size =
    static_cast<size_t>(_binary_${FONT_NAME}_end
                        - _binary_${FONT_NAME}_start);
")
endforeach()
string (APPEND FONT_HEADER_CONTENT
"
/*****************************************************************************/

/* Fonts Data */

/**
 * @brief Font Data Structure.
 */
struct s_font_data
{
    const char* name;
    const uint8_t* data;
    size_t size;
};

/**
 * @brief List of Binary Fonts Data.
 */
static s_font_data _fonts[] =
{")
foreach(FONT_FILE IN LISTS FILES_FONT)
    get_filename_component(FONT_FILENAME "${FONT_FILE}" NAME_WE)
    get_filename_component(FONT_EXT "${FONT_FILE}" EXT)
    string(MAKE_C_IDENTIFIER "${FONT_FILENAME}${FONT_EXT}" FONT_NAME)
    string(APPEND FONT_HEADER_CONTENT
"
    {
        \"${FONT_NAME}\",
        _binary_${FONT_NAME}_start,
        _binary_${FONT_NAME}_size
    },")
endforeach()
string(APPEND FONT_HEADER_CONTENT
"
};

/*****************************************************************************/

/* Usage API */

/**
 * @brief Builtin Binary Fonts.
 */
static struct s_binary_fonts
{
    constexpr size_t count() const
    {   return (sizeof(_fonts) / sizeof(_fonts[0]));   }

    constexpr s_font_data* get(const size_t index)
    {
        if (index < count())
        {   return &_fonts[index];   }

        return nullptr;
    }

    constexpr s_font_data* get(const char* name)
    {
        for (size_t i = 0U; i < count(); ++i)
        {
            if (strcmp(name, _fonts[i].name) == 0)
            {   return &_fonts[i];   }
        }

        return nullptr;
    }

} binary_fonts;

/*****************************************************************************/
")

# Create header file
file(GENERATE
    OUTPUT "${FILE_FONT_HEADER}"
    CONTENT "${FONT_HEADER_CONTENT}"
)

# Include fonts header file directory
target_include_directories(assets_font
    PUBLIC
        "${DIR_ASSETS_SRC}"
)

###############################################################################
